Module | Symmetric:
  - kipher-symmetric/**/*

Module | Gradle:
  - gradle-scripts/**/*
  - ./**/*.gradle.kts

Dependencies:
  - gradle/**/*
  - ./gradlew
  - ./gradlew.bat

Tests:
  - ./**/**/test/**/*

Documentation:
  - docs/**/*
  - ./**/*.md

Tooling:
  - .codacy.yml
  - .codecov.yml
  - .whitesource
  - detekt.yml
  - renovate.json
  - .trunk/**/*

Tooling | Workflow:
  - .github/**/*
