"Module | AES":
  - kipher-aes/**/*
  - kipher-aes-compat/**/*

"Module | RSA":
  - kipher-rsa/**/*
  - kipher-rsa-compat/**/*

"Module | Gradle":
  - gradle-scripts/**/*
  - ./**/*.gradle.kts

Dependencies:
  - gradle/**/*
  - ./gradlew
  - ./gradlew.bat

Tests:
  - ./**/**/test/**/*

Documentation:
  - docs/**/*
  - ./**/*.md

Tooling:
  - .codacy.yml
  - .codecov.yml
  - .whitesource
  - detekt.yml
  - renovate.json
  - .trunk/**/*

Tooling | Workflow:
  - .github/**/*
