"Module | AES":
  - kiper-aes/**/*
  - kiper-aes-compat/**/*

"Module | RSA":
  - kiper-rsa/**/*
  - kiper-rsa-compat/**/*

"Module | Gradle":
  - gradle-scripts/**/*
  - gradle/**/*
  - ./**/*.gradle.kts
  - gradlew
  - gradlew.bat

Tests:
  - ./**/**/test/**/*

Documentation:
  - docs/**/*
  - ./**/*.md

Tooling | Extensions:
  - renovate.json
  - .whitesource

Tooling | Workflow:
  - .github/**/*
