[versions]
kotlin = "1.8.10"
detekt = "1.22.0"
dokka = "1.7.20"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }

detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
detekt-formatting = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }

[libraries]
kotlin-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
dokka = { module = "org.jetbrains.dokka:dokka-gradle-plugin", version.ref = "dokka" }
