name: ci

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '**.txt'
      - '**.json'
      - '.gitignore'
    tags-ignore:
      - '*'

env:
  GRADLE_OPTS: -Dorg.gradle.jvmargs="-XX:MaxMetaspaceSize=2g"

jobs:
  test:
    uses: ./.github/workflows/test.yml

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Build with Analyze
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Trunk Check
        uses: trunk-io/trunk-action@v1
        with:
          post-annotations: true

      - name: Submit coverage report
        run: bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r kipher/build/reports/jacoco/testCodeCoverageReport/testCodeCoverageReport.xml
        env:
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}

      - name: Upload SARIF results file
        uses: github/codeql-action/upload-sarif@main
        with:
          sarif_file: build/reports/detekt/merge.sarif
