name: ci

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
    paths-ignore:
      - ./**.md
      - ./**.txt
      - ./**.json
      - ./.gitignore

env:
  GRADLE_OPTS: -Dorg.gradle.jvmargs="-XX:MaxMetaspaceSize=2g"
  JDK_VERSION: 19
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

permissions:
  security-events: write
  contents: write
  packages: write

jobs:
  test:
    uses: ./.github/workflows/test.yml
    secrets: inherit

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Set up JDK ${{ env.JDK_VERSION }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JDK_VERSION }}
          distribution: temurin

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - uses: gradle/gradle-build-action@v2

      - name: Gradle build
        run: ./gradlew build --scan sonar --info

      # versions are set to SNAPSHOT on main,
      # and only removed in release branch
      - name: Publish snapshots
        run: ./gradlew publish

      - name: Gradle dependency submission
        uses: mikepenz/gradle-dependency-submission@main
        with:
          gradle-build-module: |-
            :gradle-scripts
            :kipher-coverage
            :kipher-common
            :kipher-aes
            :kipher-rsa
          gradle-build-configuration: |-
            compileClasspath

      - name: Upload SARIF results file
        if: always()
        uses: github/codeql-action/upload-sarif@main
        with:
          sarif_file: build/reports/detekt/merge.sarif

      - name: Trunk Check
        if: always()
        uses: trunk-io/trunk-action@v1
        with:
          check-mode: all
          trunk-token: ${{ secrets.TRUNK_TOKEN }}
          arguments: --replace
