name: fossa

on:
  workflow_call:
  workflow_dispatch:
  push:
    paths:
      - "**.gradle.kts"
      - "libs.versions.toml"

env:
  GRADLE_OPTS: -Dorg.gradle.jvmargs="-XX:MaxMetaspaceSize=2g"
  JDK_VERSION: 20

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK ${{ env.JDK_VERSION }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JDK_VERSION }}
          distribution: "temurin"
          server-id: github
          settings-path: ${{ github.workspace }}
          cache: 'gradle'

      - name: Test with JDK ${{ env.JDK_VERSION }}
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test build

      - name: "FOSSA Scan"
        uses: fossas/fossa-action@v1
        with:
          api-key: ${{ secrets.FOSSA_API_KEY }}

      - name: "FOSSA Test"
        uses: fossas/fossa-action@v1
        with:
          api-key: ${{ secrets.FOSSA_API_KEY }}
          run-tests: true
