name: stale

on:
  schedule:
    - cron: 0 0 1 * * # Runs at 00:00 UTC on the 1st of every month.

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
      - uses: actions/stale@v9
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: No activity recorded for quite some time now. Closing the issue.
          stale-pr-message: No activity recorded for quite some time now. Closing the issue.
          stale-issue-label: Stale
          stale-pr-label: Stale
