name: tests

on:
  workflow_dispatch:
  workflow_call:

env:
  JDK_VERSION: 19
  GRADLE_OPTS: -Dorg.gradle.jvmargs="-XX:MaxMetaspaceSize=2g"

jobs:
  unit:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java: [ 11, 17, 19 ]
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    steps:
      - uses: actions/checkout@v3

      - name: Set up Java JDK
        uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JDK_VERSION }}
          distribution: temurin

      # gradle-build-action already does the caching
      - name: Setup gradle
        uses: gradle/gradle-build-action@v2
        env:
          ORG_GRADLE_PROJECT_kipher.toolchain.compilerVersion: ${{ matrix.java }}

      - name: Test with JDK ${{ matrix.java }} on Windows
        if: matrix.os == 'windows-latest'
        run: ./gradlew clean test --stacktrace --no-daemon --no-parallel

      - name: Test with JDK ${{ matrix.java }}
        if: matrix.os != 'windows-latest'
        run: ./gradlew clean test --stacktrace

      - name: Codacy coverage report
        if: matrix.os == 'ubuntu-latest' && matrix.java == 19
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: ./kipher-coverage/build/reports/jacoco/testCodeCoverageReport/testCodeCoverageReport.xml

      - name: Codecov coverage report
        if: matrix.os == 'ubuntu-latest' && matrix.java == 19
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./kipher-coverage/build/reports/jacoco/testCodeCoverageReport/testCodeCoverageReport.xml
          flags: unit
