name: tests

on:
  workflow_call:

jobs:
  unit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 8, 11, 17, 19 ]
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: "temurin"
          server-id: github
          settings-path: ${{ github.workspace }}
          cache: 'gradle'

      - name: Test with JDK ${{ matrix.java }}
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test
