name: triage

on:
  push:
    branches-ignore:
      - main
  pull_request:

env:
  GRADLE_OPTS: -Dorg.gradle.jvmargs="-XX:MaxMetaspaceSize=2g"
  JDK_VERSION: 19
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}

jobs:
  label:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/labeler@v4
        if: github.event_name == 'pull_request'
        with:
          configuration-path: .github/labels.yml
          sync-labels: true
          repo-token: ${{ secrets.GITHUB_TOKEN }}

  check:
    name: Trunk Check Annotate
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Trunk Check
        uses: trunk-io/trunk-action@main
        with:
          post-annotations: true
          trunk-token: ${{ secrets.TRUNK_TOKEN }}

  test:
    uses: ./.github/workflows/test.yml
    secrets: inherit

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK ${{ env.JDK_VERSION }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JDK_VERSION }}
          distribution: temurin

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - uses: gradle/gradle-build-action@v2

      - name: Gradle build
        run: ./gradlew build --scan
