name: triage
on:
  workflow_run:
    workflows: [ Pull Request ]
    types: [ completed ]

jobs:
  label:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/labeler@v4
        with:
          configuration-path: .github/labels.yml
          sync-labels: true
          repo-token: ${{ secrets.GITHUB_TOKEN }}

  check:
    name: Trunk Check Annotate
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Trunk Check
        uses: trunk-io/trunk-action@main
        with:
          post-annotations: true
          trunk-token: ${{ secrets.TRUNK_TOKEN }}
