name: labeler
on: [ pull_request ]

jobs:
  labeler:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/labeler@v4
        with:
          configuration-path: .github/labels.yml
          sync-labels: true
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
